package controller;
// Generated 26-jul-2013 17:12:55 by Hibernate Tools 3.2.1.GA



/**
 * Tiquete generated by hbm2java
 */
public class Tiquete  implements java.io.Serializable {


     private String TId;
     private String TCorigen;
     private String TCdestino;
     private String TFecha;
     private Integer TCsillas;
     private Integer TValor;
     private String CId;

    public Tiquete() {
    }

	
    public Tiquete(String TId) {
        this.TId = TId;
    }
    public Tiquete(String TId, String TCorigen, String TCdestino, String TFecha, Integer TCsillas, Integer TValor, String CId) {
       this.TId = TId;
       this.TCorigen = TCorigen;
       this.TCdestino = TCdestino;
       this.TFecha = TFecha;
       this.TCsillas = TCsillas;
       this.TValor = TValor;
       this.CId = CId;
    }
   
    public String getTId() {
        return this.TId;
    }
    
    public void setTId(String TId) {
        this.TId = TId;
    }
    public String getTCorigen() {
        return this.TCorigen;
    }
    
    public void setTCorigen(String TCorigen) {
        this.TCorigen = TCorigen;
    }
    public String getTCdestino() {
        return this.TCdestino;
    }
    
    public void setTCdestino(String TCdestino) {
        this.TCdestino = TCdestino;
    }
    public String getTFecha() {
        return this.TFecha;
    }
    
    public void setTFecha(String TFecha) {
        this.TFecha = TFecha;
    }
    public Integer getTCsillas() {
        return this.TCsillas;
    }
    
    public void setTCsillas(Integer TCsillas) {
        this.TCsillas = TCsillas;
    }
    public Integer getTValor() {
        return this.TValor;
    }
    
    public void setTValor(Integer TValor) {
        this.TValor = TValor;
    }
    public String getCId() {
        return this.CId;
    }
    
    public void setCId(String CId) {
        this.CId = CId;
    }

}


